FROM node:14-alpine

WORKDIR /app/backend

COPY package*.json ./

RUN npm install --production

RUN npm install -g nodemon

COPY app.js .
COPY server.js .
COPY backend ./backend

# please use ls -a in container to see 
COPY .env .


EXPOSE 5000

CMD ["npm", "start"] 