version: '3.9'

services:
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - gemini-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - gemini-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - gemini-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.admin
    container_name: admin
    ports:
      - '3001:3001'
    depends_on:
      - backend
    networks:
      - gemini-network

volumes:
  mongodb-data:

networks:
  gemini-network:
    driver: bridge
