version: '3.9'

services:
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - my-mern-app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - my-mern-app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - backend
    networks:
      - my-mern-app-network

volumes:
  mongodb-data:

networks:
  my-mern-app-network:
    driver: bridge
